format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$aws\
$sudo\
$line_break\
$status\
$container\
$shell\
$character"""

# Overwritten in lang-format
right_format = """
$direnv\
$time\
$cmd_duration"""

[aws]
format = '[$symbol($profile )(\($region\))]($style) '
symbol = 'â˜ï¸ '
style = 'purple'

[battery]
full_symbol = "â€¢ "
charging_symbol = "â‡¡ "
discharging_symbol = "â‡£ "
unknown_symbol = "â“ "
empty_symbol = "â— "

[cmd_duration]
format = "[$duration]($style)"

[directory]
style = "blue"
truncate_to_repo = false
truncation_length = 8
truncation_symbol = "â€¦/"
before_repo_root_style = "bright-black"
repo_root_style = "bold cyan"

[direnv]
disabled = false
format = '[$symbol$loaded$allowed]($style) '
symbol = ''
allowed_msg = ''
denied_msg = 'ğŸš«'
not_allowed_msg = 'Ã—'
loaded_msg = 'â–²'
unloaded_msg = ' â–³'
style = 'bold green'

[fill]
symbol = ' '

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style) "
style = "cyan"
conflicted = "â€‹"
untracked = "â€‹"
modified = "â€‹"
staged = "â€‹"
renamed = "â€‹"
deleted = "â€‹"
stashed = "â‰¡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[hostname]
ssh_symbol = ""
format = "[$hostname]($style) "
style = "bright-black"

[time]
format = '[$time]($style) '
style = "bright-black"
disabled = false

[username]
style_user = "bright-black"
format = "[$user&]($style)"
